/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package in.ris.tcdc;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int baso=0x7f020000;
        public static final int eosino=0x7f020001;
        public static final int ic_launcher=0x7f020002;
        public static final int lympho=0x7f020003;
        public static final int mono=0x7f020004;
        public static final int neutrophil=0x7f020005;
    }
    public static final class id {
        public static final int baso=0x7f060004;
        public static final int basoTotal=0x7f060003;
        public static final int choose_file_button=0x7f06000c;
        public static final int eosino=0x7f060006;
        public static final int eosinoTotal=0x7f060005;
        public static final int itemTextView=0x7f06000b;
        public static final int lympho=0x7f060008;
        public static final int lymphoTotal=0x7f060007;
        public static final int mono=0x7f06000a;
        public static final int monoTotal=0x7f060009;
        public static final int neutrophil=0x7f060002;
        public static final int neutrophilTotal=0x7f060001;
        public static final int output_textview=0x7f06000e;
        public static final int path_textview=0x7f06000d;
        public static final int total=0x7f060000;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int single_list=0x7f030001;
        public static final int storage_activity=0x7f030002;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int hello_world=0x7f040001;
    }
    public static final class style {
        public static final int AppTheme=0x7f050000;
    }
}
